using System.Globalization;
using System.Text;
using System.Xml;

// Files Icons.*.xaml → ThemedIconData.g.cs converter. See themed-icon-import.csproj for usage. Never a runtime path.

if (args.Length < 2)
{
    Console.Error.WriteLine("usage: themed-icon-import <FilesIconsStylesDir> <output ThemedIconData.g.cs> [namePrefixToStrip]");
    return 1;
}

string stylesDir = args[0];
string outPath = args[1];
string strip = args.Length >= 3 ? args[2] : "App.ThemedIcons.";

if (!Directory.Exists(stylesDir))
{
    Console.Error.WriteLine($"input directory not found: {stylesDir}");
    return 1;
}

var icons = new List<IconRecord>();
foreach (string file in Directory.EnumerateFiles(stylesDir, "Icons.*.xaml"))
    ParseFile(file, icons);

icons.Sort((a, b) => string.CompareOrdinal(a.Name, b.Name));
File.WriteAllText(outPath, Emit(icons, strip));
Console.WriteLine($"wrote {icons.Count} icons → {outPath}");
return 0;

// ── parse ────────────────────────────────────────────────────────────────────────────────────────────────────────

static void ParseFile(string path, List<IconRecord> icons)
{
    var doc = new XmlDocument();
    doc.Load(path);
    var ns = new XmlNamespaceManager(doc.NameTable);
    ns.AddNamespace("p", "http://schemas.microsoft.com/winfx/2006/xaml/presentation");
    ns.AddNamespace("x", "http://schemas.microsoft.com/winfx/2006/xaml");
    ns.AddNamespace("l", "using:Files.App.Controls");

    foreach (XmlNode styleNode in doc.SelectNodes("//p:Style", ns) ?? (IEnumerable<XmlNode>)Array.Empty<XmlNode>())
    {
        if (styleNode is not XmlElement style) continue;
        string? key = style.GetAttribute("Key", ns.LookupNamespace("x") ?? "");
        if (string.IsNullOrEmpty(key)) continue;

        var rec = new IconRecord { Name = key };
        foreach (XmlNode setterNode in style.ChildNodes)
        {
            if (setterNode is not XmlElement setter || setter.LocalName != "Setter") continue;
            string prop = setter.GetAttribute("Property");
            string val = setter.GetAttribute("Value");
            switch (prop)
            {
                case "IconSize": if (float.TryParse(val, NumberStyles.Float, CultureInfo.InvariantCulture, out float sz)) rec.ViewBox = sz; break;
                case "OutlineIconData": rec.Outline = val; break;
                case "FilledIconData": rec.Filled = val; break;
                case "Layers": ParseLayers(setter, rec); break;
            }
        }
        if (rec.Outline is not null || rec.Filled is not null || rec.Layers.Count > 0)
            icons.Add(rec);
    }
}

static void ParseLayers(XmlElement setter, IconRecord rec)
{
    foreach (XmlNode n in setter.GetElementsByTagName("ThemedIconLayer"))
    {
        if (n is not XmlElement layer) continue;
        string type = layer.GetAttribute("LayerType");
        string data = layer.GetAttribute("PathData");
        string opAttr = layer.GetAttribute("Opacity");
        if (string.IsNullOrWhiteSpace(data)) continue;
        float op = float.TryParse(opAttr, NumberStyles.Float, CultureInfo.InvariantCulture, out float o) ? o : 1f;
        rec.Layers.Add((MapRole(type), data, op));
    }
}

static string MapRole(string layerType) => layerType switch
{
    "Alt" => "Alt",
    "Accent" => "Accent",
    "AccentContrast" => "AccentContrast",
    _ => "Base",
};

// ── emit ─────────────────────────────────────────────────────────────────────────────────────────────────────────

static string Emit(List<IconRecord> icons, string strip)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("// Regenerated by tools/themed-icon-import from the Files app Icons.*.xaml.");
    sb.AppendLine("//     Copyright (c) Files Community. Licensed under the MIT License.");
    sb.AppendLine("// Keep the THIRD-PARTY-NOTICES MIT entry in sync. Files authoring view-box + EvenOdd fill preserved.");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("namespace FluentGpu.Controls;");
    sb.AppendLine();
    sb.AppendLine("internal static class ThemedIconData");
    sb.AppendLine("{");
    sb.AppendLine("    private const bool EO = true;   // WinUI PathGeometry default fill rule");
    sb.AppendLine();
    sb.AppendLine("    internal static void RegisterAll()");
    sb.AppendLine("    {");
    foreach (var rec in icons)
    {
        string name = rec.Name.StartsWith(strip, StringComparison.Ordinal) ? rec.Name.Substring(strip.Length) : rec.Name;
        sb.Append("        ThemedIconRegistry.Register(").Append(Quote(name)).Append(", new IconDef(");
        sb.Append(rec.Outline is null ? "null" : Quote(rec.Outline)).Append(", ");
        sb.Append(rec.Filled is null ? "null" : Quote(rec.Filled));
        sb.Append(", ViewBox: ").Append(rec.ViewBox.ToString(CultureInfo.InvariantCulture)).Append("f, EvenOdd: EO, Layers:");
        if (rec.Layers.Count == 0)
        {
            sb.AppendLine(" []));");
        }
        else
        {
            sb.AppendLine();
            sb.AppendLine("        [");
            foreach (var (role, data, op) in rec.Layers)
            {
                sb.Append("            new(IconRole.").Append(role).Append(", ").Append(Quote(data));
                if (op < 1f) sb.Append(", ").Append(op.ToString(CultureInfo.InvariantCulture)).Append('f');
                sb.AppendLine("),");
            }
            sb.AppendLine("        ]));");
        }
    }
    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

sealed class IconRecord
{
    public string Name = "";
    public float ViewBox = 16f;
    public string? Outline;
    public string? Filled;
    public List<(string Role, string Data, float Opacity)> Layers = new();
}
