using System;
using System.Collections.Generic;

// ── Per-page metadata (the WinUI Gallery ControlInfoData pattern) ──────────────────────────────────────────────────
// Each gallery page can carry: a tile subtitle, a long description, a tile image (bundled from WinUI-Gallery), the
// WinUI reference template path (relative to microsoft-ui-xaml controls/dev), the engine source + sample-page files
// (repo-relative), learn.microsoft.com doc links, and related-page keys. The WinUI-control half of the table is
// generated by scripts/extract-gallery-metadata.ps1 into PageInfoData.g.cs; engine pages are hand-authored here.

/// <summary>One documentation link: display title + target. <see cref="Uri"/> is absolute (https://…) or repo-relative
/// ("docs/guide/reactivity.md") — repo-relative targets open on GitHub via <see cref="PageInfo.Open"/>.</summary>
sealed record PageDoc(string Title, string Uri);

/// <summary>WinUI-Gallery-style per-page metadata. See the file header for field semantics.</summary>
sealed record PageMeta(
    string Key, string Subtitle, string Description,
    string? Image, string? WinUiTemplate, string? ControlSource, string? SamplePage,
    PageDoc[] Docs, string[] Related);

static partial class PageInfo
{
    public const string RepoBlobUrl = "https://github.com/christosk92/fluent-gpu/blob/main/";
    public const string WinUiXamlBlobUrl = "https://github.com/microsoft/microsoft-ui-xaml/blob/main/controls/dev";

    // WinUI-metadata keys that have no same-named gallery route (their demos live under engine pages) — the Related
    // section must not produce dead links for these.
    static readonly HashSet<string> NonRoutable = ["ItemsRepeater", "ScrollViewer", "AnimatedIcon"];

    // Engine capability pages (Fundamentals / Design) — docs point at the in-repo guide + design specs.
    static readonly PageMeta[] EngineMeta =
    [
        new("state", "Signals-first state: granular re-renders, bindings, reducers, context, and reactive control flow.",
            "A change reaches pixels through one mechanism: a signal. Reading a signal subscribes the current reactive computation; writing it re-runs only the computations that read it — a property binding, one component's render, or a control-flow boundary. There is no full-tree re-render and no global dirty flag.",
            null, null, "src/FluentGpu.Foundation/Signals/Signal.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — reactivity: signals, hooks, bindings", "docs/guide/reactivity.md"),
             new("Guide — pitfalls: symptom → cause → fix", "docs/guide/pitfalls.md"),
             new("Spec — reconciler & hooks (§0bis reactive model)", "design/subsystems/reconciler-hooks.md")],
            []),
        new("icons", "Every glyph in the Segoe Fluent Icons font, searchable by name, tag, or codepoint.",
            "Ui.Icon(glyph) renders a glyph run from Theme.IconFont; the Icons class holds named codepoints so glyphs stay consistent across the app. Any text run can set a FontFamily — a system name or a custom \"path/to.ttf#Family Name\" (the WinUI FontIcon syntax).",
            null, null, "src/FluentGpu.Controls/Icons.cs", "src/FluentGpu.WindowsApp/IconsPage.cs",
            [new("Segoe Fluent Icons font — reference", "https://learn.microsoft.com/windows/apps/design/style/segoe-fluent-icons-font"),
             new("Iconography in Windows apps", "https://learn.microsoft.com/windows/apps/design/style/iconography/overview"),
             new("Guide — elements, controls & theming", "docs/guide/components-elements-layout.md")],
            []),
        new("typography", "The Fluent type ramp — Caption through Display — as styled TextEl factories.",
            "A type scale built on DirectWrite glyph runs. Sizes, weights, and colors are driven by the same Text/TextEl primitives the engine renders on the GPU; the ramp matches the WinUI TextBlock styles (CaptionTextBlockStyle … DisplayTextBlockStyle).",
            null, null, "src/FluentGpu.Dsl/Typography.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Typography in Windows apps", "https://learn.microsoft.com/windows/apps/design/style/typography"),
             new("Spec — text subsystem", "design/subsystems/text.md")],
            []),
        new("flex", "Flexbox layout: main/cross-axis alignment, grow distribution, and line wrapping.",
            "The engine lays out children with a flexbox model — a main axis (justify-content) and a cross axis (align-items), with flex-grow distribution and wrapping.",
            null, null, "src/FluentGpu.Layout/FlexLayout.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — components, elements & layout", "docs/guide/components-elements-layout.md"),
             new("Spec — layout subsystem", "design/subsystems/layout.md")],
            []),
        new("grid", "Two-dimensional layout with real tracks: fixed px, fractional stars, and auto sizing.",
            "Like CSS Grid, columns can be fixed pixels, fractional star units that share leftover space, or auto-sized to content; cells flow row by row at a uniform row height.",
            null, null, "src/FluentGpu.Layout/FlexLayout.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — components, elements & layout", "docs/guide/components-elements-layout.md"),
             new("Spec — layout subsystem", "design/subsystems/layout.md")],
            []),
        new("virtualization", "Uniform, grid, measured, and lined-flow virtualization with slot recycling.",
            "Visible slots are built once and rebound via index signals as you scroll — no element rebuild, no reconcile, no node churn. Off-screen realizations recycle over the slab free-list, so a 100k-row list scrolls with zero managed allocation.",
            null, null, "src/FluentGpu.Controls/Virtual.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — rendering & performance", "docs/guide/rendering-and-performance.md"),
             new("Spec — virtualization subsystem", "design/subsystems/virtualization.md")],
            []),
        new("animation", "The full AnimEngine: tweens, keyframes, springs, driven timelines, reveals, FLIP, and smooth reflow.",
            "Tracks are eased keyframes (any curve or authored KeySpline), physical springs with velocity-carrying retarget, or value-driven timelines, on a fixed channel set — transform, opacity, clip, stroke trim, presented size, and layout size. LayoutTransition makes the same engine declarative: position FLIP, scale-correct, live re-wrap, smooth reflow (SizeMode.Reflow), and enter/exit terminals with stagger.",
            null, null, "src/FluentGpu.Animation/AnimEngine.cs", "src/FluentGpu.WindowsApp/AnimationPage.cs",
            [new("Guide — control fidelity (motion & visual states)", "docs/guide/control-fidelity.md"),
             new("Spec — backdrop, effects & animation", "design/subsystems/backdrop-effects-animation.md")],
            []),
        new("compositor", "Per-node transform and opacity, applied at record time with no relayout.",
            "Transform and opacity are composited per node — rotation, scale, offset, and alpha apply at record time without reflowing siblings.",
            null, null, "src/FluentGpu.Render/SceneRecorder.cs", "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — rendering & performance", "docs/guide/rendering-and-performance.md"),
             new("Spec — GPU renderer", "design/subsystems/gpu-renderer.md")],
            []),
        new("scrolling", "Layout-free scrolling: the viewport clips, a transform offsets the content.",
            "Scrolling never relayouts: the viewport clips and the content is offset by a single transform, with smooth inertial wheel deltas and auto-hiding scrollbars.",
            null, null, null, "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — rendering & performance", "docs/guide/rendering-and-performance.md"),
             new("Spec — layout subsystem", "design/subsystems/layout.md")],
            []),
        new("images", "Async images: HTTP fetch, off-thread WIC decode, disk cache, GPU texture residency.",
            "Images fetch over HTTP/2, decode off-thread on the worker pool (constrained to display size), cache to disk, and upload to GPU textures; a placeholder tint shows until each decode lands.",
            null, null, null, "src/FluentGpu.WindowsApp/GalleryPages.cs",
            [new("Guide — components, elements & layout", "docs/guide/components-elements-layout.md"),
             new("Spec — media pipeline", "design/subsystems/media-pipeline.md")],
            []),
        new("repeater", "A data-driven repeating layout panel over the virtualization substrate.",
            "ItemsRepeater-style repetition: a count + item template, laid out by stack or grid layouts over the engine's virtualization substrate.",
            null, "/Repeater", "src/FluentGpu.Controls/Repeater.cs", "src/FluentGpu.WindowsApp/RepeaterPage.cs",
            [new("ItemsRepeater - API", "https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.itemsrepeater"),
             new("Spec — virtualization subsystem", "design/subsystems/virtualization.md")],
            []),
    ];

    // Built lazily on first use: static field initializers across PARTIAL class files run in unspecified order, so an
    // eager `= BuildIndex()` here can run before the generated WinUiMeta initializer (NullReference at startup).
    static Dictionary<string, PageMeta>? _byKey;

    static Dictionary<string, PageMeta> ByKey => _byKey ??= BuildIndex();

    static Dictionary<string, PageMeta> BuildIndex()
    {
        var map = new Dictionary<string, PageMeta>(StringComparer.Ordinal);
        foreach (var m in WinUiMeta) map[m.Key] = m;
        foreach (var m in EngineMeta) map[m.Key] = m;
        return map;
    }

    /// <summary>Metadata for a page key (control pages use the control name; engine pages the nav key). Null when the
    /// page has no registered metadata — the shell falls back to a plain title + description header.</summary>
    public static PageMeta? Find(string key) => ByKey.TryGetValue(key, out var m) ? m : null;

    /// <summary>Related keys that actually route to a gallery page (drops WinUI-only entries).</summary>
    public static string[] RoutableRelated(PageMeta meta)
    {
        var list = new List<string>(meta.Related.Length);
        foreach (var r in meta.Related)
            if (!NonRoutable.Contains(r) && ByKey.ContainsKey(r)) list.Add(r);
        return list.ToArray();
    }

    /// <summary>Launch a doc/source link: absolute URIs open as-is; repo-relative paths open on GitHub. Routed through
    /// the <c>IPlatformApp.OpenUri</c> PAL seam (ShellExecute on Windows; recorded in headless hosts).</summary>
    public static void Open(string uri)
        => FluentGpu.Hooks.InputHooks.Current.Default.OpenUri?.Invoke(
            uri.StartsWith("http", StringComparison.Ordinal) ? uri : RepoBlobUrl + uri.Replace('\\', '/'));
}
