<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
    <PublishAot>false</PublishAot>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bench.Contracts\Bench.Contracts.csproj" />
  </ItemGroup>
</Project>
