using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentGpu.SourceGen.Interop
{
    /// <summary>
    /// <b>GEN-COM — ComInteropGenerator</b> (design/subsystems/com-interop.md; the COM-binding scaffold reserved in
    /// <c>Placeholder.cs</c>). Harvests a checked-in, machine-generated <c>*.comabi.json</c> (passed as an
    /// <c>AdditionalFiles</c> item) and emits hand-vtable <c>IComObject</c> consume bindings — <c>calli</c> thunks
    /// through the <c>T** lpVtbl</c> at the JSON's absolute slot indices — plus IID <c>ReadOnlySpan&lt;byte&gt;</c>
    /// spans. <b>No human ever types a slot index</b> (the FGCOM0006 contract). It is Win32-free AT THE SOURCE LEVEL
    /// (no TerraFX/Win32 PackageReference enters this analyzer), so it lives in the consolidated FluentGpu.SourceGen.
    ///
    /// <para><b>STATUS (source-gen investigation):</b> build-later — footprint/portability value (drops the large TerraFX
    /// surface from the trimmed AOT binary; enables the TerraFX-free macOS seam), NOT a frame-speed win (TerraFX already
    /// does zero-alloc <c>calli</c>). It depends on the unbuilt <c>FluentGpu.AbiHarvest</c> (winmd × ClangSharp) to
    /// PRODUCE a <c>*.comabi.json</c>; until one is checked in, this generator is DORMANT (no matching AdditionalFiles ⇒
    /// emits nothing). Wave 1 lands the harvester/emitter shape; the full <c>calli</c> emission + the callee CCW vtables
    /// land when a real manifest + the runtime self-check exist. The <c>FGCOM####</c> analyzers ship alongside.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ComInteropGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Trigger: any AdditionalFiles item named *.comabi.json. (None in the repo ⇒ dormant.)
            var manifests = context.AdditionalTextsProvider
                .Where(static f => f.Path.EndsWith(".comabi.json", System.StringComparison.OrdinalIgnoreCase))
                .Select(static (f, _) => Path.GetFileNameWithoutExtension(f.Path).Replace(".comabi", ""));

            context.RegisterSourceOutput(manifests, static (spc, name) =>
            {
                string cls = Sanitize(name);
                spc.AddSource(cls + ".ComBindings.g.cs", SourceText.From(Emit(cls), Encoding.UTF8));
            });
        }

        private static string Emit(string cls)
        {
            // Dormant emission shape: a binding holder per manifest. The per-method calli thunks + IID u8 spans are
            // generated from the JSON's reconciled absolute slots when a real *.comabi.json is harvested. Kept Win32-free.
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n// Generated by FluentGpu.SourceGen (Interop/ComInteropGenerator, GEN-COM) — DO NOT EDIT.\n");
            sb.Append("// Hand-vtable IComObject consume bindings harvested from a *.comabi.json (no human-typed slots; FGCOM0006).\n#nullable enable\n\n");
            sb.Append("namespace FluentGpu.Interop.Generated\n{\n");
            sb.Append("    /// <summary>Generated hand-vtable bindings for the ").Append(cls).Append(" ABI manifest.</summary>\n");
            sb.Append("    internal static unsafe partial class ").Append(cls).Append("Bindings\n    {\n");
            sb.Append("        // Per the manifest, each method emits a `calli` through `(*lpVtbl)[slot]` at its absolute\n");
            sb.Append("        // reconciled slot, with an asserted-blittable signature; non-blittable methods route to the\n");
            sb.Append("        // cold [GeneratedComInterface] path (or fail the build). IIDs emit as `ReadOnlySpan<byte>` u8.\n");
            sb.Append("    }\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        private static string Sanitize(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (char c in s) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            string r = sb.ToString();
            return r.Length == 0 || char.IsDigit(r[0]) ? "Com" + r : r;
        }
    }
}
