using System.Collections.Generic;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentGpu.SourceGen.Interop
{
    /// <summary>
    /// <b>GEN-COM — ComInteropGenerator</b> (design/subsystems/com-interop.md; the COM-binding scaffold reserved in
    /// <c>Placeholder.cs</c>). Harvests a checked-in <c>*.comabi.json</c> (an <c>AdditionalFiles</c> item) and emits, per
    /// interface, its IID + hand-vtable <c>calli</c> consume bindings — a function-pointer call through the absolute
    /// reconciled <c>vtable[slot]</c>. <b>No human types a slot index</b> (the FGCOM0006 contract); the slots come from
    /// the JSON. Win32-free at the source level, so it lives in the consolidated FluentGpu.SourceGen and is referenced as
    /// an analyzer by the Windows leaves.
    ///
    /// <para><b>STATUS (source-gen investigation):</b> build-later — footprint/portability value (drops the TerraFX
    /// surface; enables the TerraFX-free macOS seam), NOT a frame-speed win (TerraFX already does zero-alloc <c>calli</c>).
    /// A real, AbiHarvest-produced, runtime-self-checked manifest is the eventual input; the checked-in sample drives the
    /// emission today. The generated bindings are additive (not wired into the live render path) until the migration.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ComInteropGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var manifests = context.AdditionalTextsProvider
                .Where(static f => f.Path.EndsWith(".comabi.json", System.StringComparison.OrdinalIgnoreCase))
                .Select(static (f, ct) => (Name: Path.GetFileName(f.Path), Json: f.GetText(ct)?.ToString() ?? ""));

            context.RegisterSourceOutput(manifests, static (spc, m) =>
            {
                var ifaces = ComAbi.Parse(m.Json);
                if (ifaces.Count == 0) return;
                string hint = Sanitize(m.Name.Replace(".comabi.json", "").Replace(".json", "")) + ".ComBindings.g.cs";
                spc.AddSource(hint, SourceText.From(Emit(m.Name, ifaces), Encoding.UTF8));
            });
        }

        private static string Emit(string manifest, List<ComAbi.Iface> ifaces)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n// Generated by FluentGpu.SourceGen (Interop/ComInteropGenerator, GEN-COM) from ")
              .Append(manifest).Append(" — DO NOT EDIT.\n");
            sb.Append("// Hand-vtable IComObject consume bindings: a calli through vtable[slot] at slots harvested from the\n");
            sb.Append("// manifest (no human-typed slots; FGCOM0006). Additive — not wired into the live render path yet.\n");
            sb.Append("#nullable enable\n\nnamespace FluentGpu.Interop.Generated\n{\n");
            foreach (ComAbi.Iface f in ifaces)
            {
                sb.Append("    /// <summary>Generated hand-vtable bindings for ").Append(f.Name).Append(".</summary>\n");
                sb.Append("    internal static unsafe class ").Append(f.Name).Append("Vtbl\n    {\n");
                if (f.Iid.Length > 0)
                    sb.Append("        public static readonly global::System.Guid IID = new global::System.Guid(\"").Append(f.Iid).Append("\");\n");
                foreach (ComAbi.Method method in f.Methods)
                {
                    // Typed calli through the COM vtable: (*(void***)self)[slot] is the fn-ptr; first arg is `this`.
                    string sig = "void*", parms = "void* self", args = "self";
                    for (int i = 0; i < method.Params.Length; i++)
                    {
                        sig += ", " + method.Params[i];
                        parms += ", " + method.Params[i] + " p" + i;
                        args += ", p" + i;
                    }
                    sig += ", " + method.Ret;
                    sb.Append("        /// <summary>vtable slot ").Append(method.Slot).Append(".</summary>\n");
                    sb.Append("        public static ").Append(method.Ret).Append(' ').Append(method.Name).Append('(').Append(parms)
                      .Append(") => ((delegate* unmanaged<").Append(sig).Append(">)(*(void***)self)[").Append(method.Slot).Append("])(").Append(args).Append(");\n");
                }
                sb.Append("    }\n");
            }
            sb.Append("}\n");
            return sb.ToString();
        }

        private static string Sanitize(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (char c in s) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            string r = sb.ToString();
            return r.Length == 0 || char.IsDigit(r[0]) ? "Com" + r : r;
        }
    }

    /// <summary>A compact, dependency-free reader for the comabi manifest: <c>{ "interfaces": [ { "name", "iid",
    /// "methods": [ { "name", "slot" } ] } ] }</c>. A netstandard2.0 generator can't rely on System.Text.Json, and the
    /// loc TinyJsonReader only handles flat string objects, so this hand-rolls objects/arrays/strings/numbers.</summary>
    internal static class ComAbi
    {
        internal readonly struct Method
        {
            public Method(string name, int slot, string ret, string[] @params) { Name = name; Slot = slot; Ret = ret; Params = @params; }
            public string Name { get; }
            public int Slot { get; }
            public string Ret { get; }       // C# return type ("int" = HRESULT default; "void"; "ulong"; ...)
            public string[] Params { get; }  // C# param types AFTER `this` (e.g. "ulong", "void*")
        }

        internal readonly struct Iface
        {
            public Iface(string name, string iid, List<Method> methods) { Name = name; Iid = iid; Methods = methods; }
            public string Name { get; }
            public string Iid { get; }
            public List<Method> Methods { get; }
        }

        public static List<Iface> Parse(string json)
        {
            var result = new List<Iface>();
            object? root = new P(json).ParseValue();
            if (root is not Dictionary<string, object?> obj || obj.TryGetValue("interfaces", out object? ix) is false || ix is not List<object?> arr)
                return result;
            foreach (object? item in arr)
            {
                if (item is not Dictionary<string, object?> io) continue;
                string name = SanitizeId(Str(io, "name"));
                if (name.Length == 0) continue;
                var methods = new List<Method>();
                if (io.TryGetValue("methods", out object? ms) && ms is List<object?> ma)
                {
                    foreach (object? mo in ma)
                    {
                        if (mo is not Dictionary<string, object?> md) continue;
                        string mn = SanitizeId(Str(md, "name"));
                        if (mn.Length == 0) continue;
                        string ret = Str(md, "ret"); if (ret.Length == 0) ret = "int";
                        var ps = new List<string>();
                        if (md.TryGetValue("params", out object? pv) && pv is List<object?> pa)
                            foreach (object? p in pa) if (p is string ptype) ps.Add(ptype);
                        methods.Add(new Method(mn, (int)Num(md, "slot"), ret, ps.ToArray()));
                    }
                }
                result.Add(new Iface(name, Str(io, "iid"), methods));
            }
            return result;
        }

        private static string Str(Dictionary<string, object?> o, string k) => o.TryGetValue(k, out object? v) && v is string s ? s : "";
        private static double Num(Dictionary<string, object?> o, string k) => o.TryGetValue(k, out object? v) && v is double d ? d : 0;

        private static string SanitizeId(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (char c in s) if (char.IsLetterOrDigit(c) || c == '_') sb.Append(c);
            return sb.ToString();
        }

        // Minimal recursive-descent JSON parser (objects, arrays, strings, numbers, true/false/null).
        private sealed class P
        {
            private readonly string _s;
            private int _i;
            public P(string s) { _s = s ?? ""; }

            public object? ParseValue()
            {
                Ws();
                if (_i >= _s.Length) return null;
                char c = _s[_i];
                switch (c)
                {
                    case '{': return Obj();
                    case '[': return Arr();
                    case '"': return Str();
                    case 't': _i += 4; return true;
                    case 'f': _i += 5; return false;
                    case 'n': _i += 4; return null;
                    default: return Num();
                }
            }

            private Dictionary<string, object?> Obj()
            {
                var d = new Dictionary<string, object?>();
                _i++; Ws();
                if (_i < _s.Length && _s[_i] == '}') { _i++; return d; }
                while (_i < _s.Length)
                {
                    Ws();
                    string key = Str();
                    Ws();
                    if (_i < _s.Length && _s[_i] == ':') _i++;
                    d[key] = ParseValue();
                    Ws();
                    if (_i < _s.Length && _s[_i] == ',') { _i++; continue; }
                    if (_i < _s.Length && _s[_i] == '}') { _i++; break; }
                    break;
                }
                return d;
            }

            private List<object?> Arr()
            {
                var a = new List<object?>();
                _i++; Ws();
                if (_i < _s.Length && _s[_i] == ']') { _i++; return a; }
                while (_i < _s.Length)
                {
                    a.Add(ParseValue());
                    Ws();
                    if (_i < _s.Length && _s[_i] == ',') { _i++; continue; }
                    if (_i < _s.Length && _s[_i] == ']') { _i++; break; }
                    break;
                }
                return a;
            }

            private string Str()
            {
                var sb = new StringBuilder();
                if (_i >= _s.Length || _s[_i] != '"') return "";
                _i++;
                while (_i < _s.Length)
                {
                    char c = _s[_i++];
                    if (c == '"') break;
                    if (c == '\\' && _i < _s.Length) { sb.Append(_s[_i++]); continue; }
                    sb.Append(c);
                }
                return sb.ToString();
            }

            private double Num()
            {
                int start = _i;
                while (_i < _s.Length && ("0123456789+-.eE".IndexOf(_s[_i]) >= 0)) _i++;
                return double.TryParse(_s.Substring(start, _i - start), System.Globalization.NumberStyles.Any,
                    System.Globalization.CultureInfo.InvariantCulture, out double v) ? v : 0;
            }

            private void Ws() { while (_i < _s.Length && (_s[_i] == ' ' || _s[_i] == '\t' || _s[_i] == '\r' || _s[_i] == '\n')) _i++; }
        }
    }
}
