import type {
  CuratedLayout,
  CuratedSection,
  DesignMeta,
  LibraryItem,
  ModePreferences,
  SectionKind,
  SidebarDesign,
} from "./types";

export const designMeta: DesignMeta[] = [
  {
    id: "classic",
    title: "Classic",
    eyebrow: "Familiar and focused",
    description: "Wavee’s original shortcuts, pinned items and playlist sections.",
  },
  {
    id: "library",
    title: "Library",
    eyebrow: "Unified and powerful",
    description: "Filter, search, sort and browse your whole library in one place.",
  },
  {
    id: "curated",
    title: "Wavee Curated",
    eyebrow: "Yours, by design",
    description: "Arrange the sections you use, then tune every detail.",
  },
];

export const initialModePreferences: ModePreferences = {
  classic: { width: 280, collapsed: false },
  library: { width: 340, collapsed: false },
  curated: { width: 320, collapsed: false },
};

export const libraryItems: LibraryItem[] = [
  {
    id: "liked",
    title: "Liked Songs",
    kind: "route",
    subtitle: "842 songs",
    creator: "Christos",
    route: "liked",
    icon: "heart",
    art: "linear-gradient(135deg, #526dff 0%, #7d4dd6 48%, #e7e9ff 100%)",
    count: 842,
    added: 30,
    visited: 98,
  },
  {
    id: "midnight-city",
    title: "Midnight City Drives",
    kind: "playlist",
    subtitle: "By you · 64 songs",
    creator: "Christos",
    qualifier: "you",
    route: "playlist:midnight-city",
    art: "linear-gradient(145deg, #091d37 4%, #365f95 42%, #ef855e 100%)",
    count: 64,
    added: 97,
    visited: 95,
  },
  {
    id: "velvet-mornings",
    title: "Velvet Mornings",
    kind: "playlist",
    subtitle: "By you · 31 songs",
    creator: "Christos",
    qualifier: "you",
    route: "playlist:velvet-mornings",
    art: "linear-gradient(145deg, #4a2f25, #bd7963 52%, #f5d6aa)",
    count: 31,
    added: 92,
    visited: 70,
  },
  {
    id: "discover-weekly",
    title: "Discover Weekly",
    kind: "playlist",
    subtitle: "By Spotify · 30 songs",
    creator: "Spotify",
    qualifier: "spotify",
    route: "playlist:discover-weekly",
    art: "linear-gradient(135deg, #1f1511 0%, #9d674b 52%, #d8b692 100%)",
    count: 30,
    added: 90,
    visited: 88,
  },
  {
    id: "daylist",
    title: "daylist",
    kind: "playlist",
    subtitle: "By Spotify · 50 songs",
    creator: "Spotify",
    qualifier: "spotify",
    route: "playlist:daylist",
    art: "linear-gradient(135deg, #f6c646 0%, #f1e8a4 48%, #4f8b89 100%)",
    count: 50,
    added: 88,
    visited: 82,
  },
  {
    id: "design-mode",
    title: "Design mode",
    kind: "playlist",
    subtitle: "Collaborative · 48 songs",
    creator: "Maya + Christos",
    qualifier: "mixed",
    route: "playlist:design-mode",
    art: "linear-gradient(150deg, #341f5d, #8459d4 48%, #ff9cbb)",
    count: 48,
    added: 84,
    visited: 63,
  },
  {
    id: "jazz-cafe",
    title: "Jazz café",
    kind: "folder",
    subtitle: "Folder · 3 playlists",
    creator: "",
    route: "",
    icon: "folder",
    art: "linear-gradient(145deg, #283a33, #7c9b79)",
    childIds: ["blue-notes", "late-night-jazz", "coffee-table"],
    added: 70,
    visited: 55,
  },
  {
    id: "blue-notes",
    title: "Blue notes",
    kind: "playlist",
    subtitle: "By you · 38 songs",
    creator: "Christos",
    qualifier: "you",
    route: "playlist:blue-notes",
    art: "linear-gradient(140deg, #142642, #2d70b0 50%, #d0dff2)",
    count: 38,
    folderId: "jazz-cafe",
    added: 76,
    visited: 61,
  },
  {
    id: "late-night-jazz",
    title: "Late night jazz",
    kind: "playlist",
    subtitle: "By Spotify · 80 songs",
    creator: "Spotify",
    qualifier: "spotify",
    route: "playlist:late-night-jazz",
    art: "linear-gradient(145deg, #171525, #4e507c 45%, #a69bce)",
    count: 80,
    folderId: "jazz-cafe",
    added: 66,
    visited: 46,
  },
  {
    id: "coffee-table",
    title: "Coffee table",
    kind: "playlist",
    subtitle: "Collaborative · 27 songs",
    creator: "Anna + Christos",
    qualifier: "mixed",
    route: "playlist:coffee-table",
    art: "linear-gradient(140deg, #36241a, #a57855 58%, #d9ba92)",
    count: 27,
    folderId: "jazz-cafe",
    added: 62,
    visited: 32,
  },
  {
    id: "brat",
    title: "BRAT",
    kind: "album",
    subtitle: "Album · Charli xcx",
    creator: "Charli xcx",
    route: "album:brat",
    art: "linear-gradient(135deg, #8ace00, #b8eb23)",
    count: 15,
    added: 94,
    visited: 84,
  },
  {
    id: "short-n-sweet",
    title: "Short n’ Sweet",
    kind: "album",
    subtitle: "Album · Sabrina Carpenter",
    creator: "Sabrina Carpenter",
    route: "album:short-n-sweet",
    art: "linear-gradient(145deg, #91c5e1 0%, #d8e4ed 52%, #9d725c 100%)",
    count: 12,
    added: 91,
    visited: 90,
  },
  {
    id: "imaginal-disk",
    title: "Imaginal Disk",
    kind: "album",
    subtitle: "Album · Magdalena Bay",
    creator: "Magdalena Bay",
    route: "album:imaginal-disk",
    art: "radial-gradient(circle at 65% 35%, #ffe8b7, #de76a6 38%, #554792 72%, #151837)",
    count: 15,
    added: 79,
    visited: 76,
  },
  {
    id: "daft-punk",
    title: "Daft Punk",
    kind: "artist",
    subtitle: "Artist",
    creator: "Daft Punk",
    route: "artist:daft-punk",
    art: "radial-gradient(circle at 50% 42%, #e0c184, #3a332d 40%, #0b0b0b 72%)",
    added: 75,
    visited: 93,
  },
  {
    id: "caroline",
    title: "Caroline Polachek",
    kind: "artist",
    subtitle: "Artist",
    creator: "Caroline Polachek",
    route: "artist:caroline-polachek",
    art: "radial-gradient(circle at 40% 35%, #ffdab4, #a24d66 48%, #2b1836)",
    added: 69,
    visited: 58,
  },
  {
    id: "fred-again",
    title: "Fred again..",
    kind: "artist",
    subtitle: "Artist",
    creator: "Fred again..",
    route: "artist:fred-again",
    art: "radial-gradient(circle at 50% 30%, #c7d9ec, #8c9aab 42%, #24282d)",
    added: 63,
    visited: 68,
  },
  {
    id: "daily",
    title: "The Daily",
    kind: "podcast",
    subtitle: "Podcast · The New York Times",
    creator: "The New York Times",
    route: "podcast:daily",
    art: "linear-gradient(135deg, #f5f5f5 0 48%, #111 48% 100%)",
    added: 80,
    visited: 74,
  },
  {
    id: "decoder",
    title: "Decoder with Nilay Patel",
    kind: "podcast",
    subtitle: "Podcast · The Verge",
    creator: "The Verge",
    route: "podcast:decoder",
    art: "linear-gradient(140deg, #e53a2f, #ef7d68 45%, #471a1b)",
    added: 72,
    visited: 52,
  },
  {
    id: "song-exploder",
    title: "Song Exploder",
    kind: "podcast",
    subtitle: "Podcast · Hrishikesh Hirway",
    creator: "Hrishikesh Hirway",
    route: "podcast:song-exploder",
    art: "linear-gradient(135deg, #ffd742, #ef6e29 48%, #232d5f)",
    added: 64,
    visited: 40,
  },
];

export const shortcutItems: LibraryItem[] = [
  {
    id: "home",
    title: "Home",
    kind: "route",
    subtitle: "",
    creator: "",
    route: "home",
    icon: "home",
    art: "linear-gradient(135deg, #30416d, #718ec5)",
    added: 0,
    visited: 100,
  },
  {
    id: "search",
    title: "Search",
    kind: "route",
    subtitle: "",
    creator: "",
    route: "search",
    icon: "search",
    art: "linear-gradient(135deg, #43315e, #8a6ab0)",
    added: 0,
    visited: 99,
  },
  libraryItems[0],
  {
    id: "albums",
    title: "Albums",
    kind: "route",
    subtitle: "12 saved",
    creator: "",
    route: "albums",
    icon: "album",
    art: "linear-gradient(135deg, #654827, #c9995e)",
    count: 12,
    added: 0,
    visited: 65,
  },
  {
    id: "artists",
    title: "Artists",
    kind: "route",
    subtitle: "23 followed",
    creator: "",
    route: "artists",
    icon: "artist",
    art: "linear-gradient(135deg, #345a50, #8abfb0)",
    count: 23,
    added: 0,
    visited: 64,
  },
  {
    id: "podcasts",
    title: "Podcasts",
    kind: "route",
    subtitle: "9 shows",
    creator: "",
    route: "podcasts",
    icon: "podcast",
    art: "linear-gradient(135deg, #5a3550, #b7759d)",
    count: 9,
    added: 0,
    visited: 62,
  },
  {
    id: "local",
    title: "Local files",
    kind: "route",
    subtitle: "128 songs",
    creator: "",
    route: "local",
    icon: "folder",
    art: "linear-gradient(135deg, #3d4f5a, #8d9ca4)",
    count: 128,
    added: 0,
    visited: 31,
  },
  {
    id: "history",
    title: "Listening history",
    kind: "route",
    subtitle: "",
    creator: "",
    route: "history",
    icon: "history",
    art: "linear-gradient(135deg, #464464, #9490bd)",
    added: 0,
    visited: 46,
  },
];

export const allItems = [...shortcutItems.filter((item, index) => index < 2), ...libraryItems, ...shortcutItems.slice(3)];

let nextSection = 100;

export function section(kind: SectionKind, title: string, partial: Partial<CuratedSection> = {}): CuratedSection {
  nextSection += 1;
  return {
    id: `section-${nextSection}`,
    kind,
    title,
    hidden: false,
    collapsed: false,
    density: "cozy",
    presentation: "list",
    showArtwork: !["shortcuts", "heading", "divider"].includes(kind),
    showSubtitles: !["shortcuts", "heading", "divider"].includes(kind),
    showInRail: !["jumpBack", "heading"].includes(kind),
    maxItems: 0,
    itemIds: [],
    ...partial,
  };
}

export function buildTemplate(templateId: string): CuratedLayout {
  const templates: Record<string, () => CuratedSection[]> = {
    curated: () => [
      section("pinned", "Pinned"),
      section("divider", ""),
      section("jumpBack", "Jump back in", { maxItems: 4, showInRail: false }),
      section("divider", ""),
      section("shortcuts", "Your Library", {
        itemIds: ["liked", "albums", "artists", "podcasts", "local"],
        showArtwork: false,
        showSubtitles: false,
      }),
      section("divider", ""),
      section("playlists", "Playlists"),
    ],
    classic: () => [
      section("pinned", "Pinned", { showInRail: false }),
      section("shortcuts", "Your Library", {
        itemIds: ["albums", "artists", "liked", "podcasts", "local"],
        showArtwork: false,
        showSubtitles: false,
      }),
      section("divider", ""),
      section("playlists", "Playlists"),
      section("heading", "Developer"),
      section("shortcuts", "", {
        itemIds: ["history"],
        showArtwork: false,
        showSubtitles: false,
      }),
    ],
    library: () => [
      section("pinned", "Pinned"),
      section("divider", ""),
      section("library", "Your Library", { maxItems: 14 }),
      section("divider", ""),
      section("shortcuts", "Explore", {
        itemIds: ["home", "search"],
        showArtwork: false,
        showSubtitles: false,
      }),
    ],
    minimal: () => [
      section("shortcuts", "", {
        itemIds: ["liked", "albums", "artists"],
        density: "compact",
        showArtwork: false,
        showSubtitles: false,
        showInRail: true,
      }),
      section("divider", ""),
      section("playlists", "Playlists", {
        density: "compact",
        showArtwork: false,
        showSubtitles: false,
      }),
    ],
    blank: () => [],
  };

  const safeId = templates[templateId] ? templateId : "curated";
  return { templateId: safeId, sections: templates[safeId]() };
}

export const templateMeta = [
  { id: "curated", name: "Wavee Curated", description: "Pins, recents, shortcuts and playlists." },
  { id: "classic", name: "Classic-inspired", description: "The familiar Wavee shape, now editable." },
  { id: "library", name: "Library-inspired", description: "One unified library with pins on top." },
  { id: "minimal", name: "Minimal", description: "Just essentials and a compact playlist list." },
  { id: "blank", name: "Blank", description: "Start from nothing." },
];

export const modeDefaultWidth: Record<SidebarDesign, number> = {
  classic: 280,
  library: 340,
  curated: 320,
};
