using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentGpu.SourceGen.Engine
{
    // ════════════════════════════════════════════════════════════════════════════════════════════════════════════
    //  GATED MIGRATIONS — the risky generators that touch the verified-green core. Each emits ONLY when its opt-in
    //  marker is applied; the markers are emitted internal/post-init and applied NOWHERE in the engine, so these are
    //  default-OFF (dormant) and cannot regress the 528 VerticalSlice gates. Flipping one on emits the new machinery;
    //  the matching LIVE-code switch-over (which a generator cannot do — it is additive) is the deliberate migration,
    //  intentionally NOT performed here. Per the user's "full toolkit now, gated" directive.
    // ════════════════════════════════════════════════════════════════════════════════════════════════════════════

    /// <summary>Opt-in markers for the gated migrations (internal, post-init). Applied nowhere ⇒ default-off.</summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class GatedMigrationMarkers : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context) =>
            context.RegisterPostInitializationOutput(static ctx =>
                ctx.AddSource("FluentGpu.CodeGen.GatedMigrationAttributes.g.cs", SourceText.From(Src, Encoding.UTF8)));

        private const string Src =
@"// <auto-generated/>
// Opt-in markers for the gated, risky migrations (default-OFF: applied nowhere). Internal per-assembly.
#nullable enable
namespace FluentGpu.CodeGen
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class EnableHookDepsLoweringAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class EnableColdSlabAttribute : global::System.Attribute { }
}
";
    }

    /// <summary>
    /// <b>GEN-02 — HookDeps lowering infrastructure (GATED, default-off).</b> When a class is marked
    /// <c>[EnableHookDepsLowering]</c>, emit the §3.3/§3.4 machinery that the general <c>params object[]</c>-deps killer
    /// needs: <c>GcDepTable</c> (object?[] parked per render, ReferenceEquals), the <c>[InlineArray(4)] DepInline4</c>
    /// overflow, and the <c>DepDeps</c> store. Verdict: medium impact (reconcile-edge GC), but a DELIBERATE migration —
    /// the shipped Kind-less two-long <c>DepKey</c> (Hooks/DepKey.cs) underpins the 521-gate animation rework and its
    /// DepKind tag does not coexist with the 4-scalar packing (see reconciler-hooks.md §3.2 status note). Dormant
    /// (marker applied nowhere); flipping it on is step 2 of the GEN-02 sequence after the DepKey canon decision.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class HookDepsInfraGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var on = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.EnableHookDepsLoweringAttribute",
                    static (_, _) => true, static (_, _) => true);
            context.RegisterSourceOutput(on, static (spc, _) =>
                spc.AddSource("FluentGpu.Hooks.GcDepTable.g.cs", SourceText.From(HookDepsInfra, Encoding.UTF8)));
        }

        private const string HookDepsInfra =
@"// <auto-generated/>
// GEN-02 HookDeps lowering infrastructure (emitted because [EnableHookDepsLowering] is present). reconciler-hooks.md §3.3/§3.4.
#nullable enable
namespace FluentGpu.Hooks
{
    /// <summary>Side-buffer for reference/delegate deps that cannot live in a pure-scalar DepKey (compared by ReferenceEquals).</summary>
    internal sealed class GcDepTable
    {
        private object?[] _prev = global::System.Array.Empty<object?>();
        private object?[] _cur = new object?[8];
        private int _curCount;
        public int Park(object? o) { if (_curCount == _cur.Length) global::System.Array.Resize(ref _cur, _cur.Length * 2); _cur[_curCount] = o; return _curCount++; }
        public bool RefEqualPrev(int slot, int prevSlot) => global::System.Object.ReferenceEquals(_cur[slot], (uint)prevSlot < (uint)_prev.Length ? _prev[prevSlot] : null);
        public void EndRender() { (_prev, _cur) = (_cur, _prev); _curCount = 0; global::System.Array.Clear(_cur, 0, _cur.Length); }
    }

    [global::System.Runtime.CompilerServices.InlineArray(4)]
    internal struct DepInline4 { private DepKey _e0; }

    internal struct DepDeps
    {
        public byte Count;
        public bool HasDeps;
        public DepInline4 Inline;
        public DepKey[]? Overflow;
    }
}
";
    }

    /// <summary>
    /// <b>GEN-17 — cold side-table slab (GATED, default-off).</b> When a class is marked <c>[EnableColdSlab]</c>, emit a
    /// dense cold-slab (slab + ref column) to replace a <c>Dictionary&lt;int, T&gt;</c> per-node side table. Verdict:
    /// medium impact (per-frame CPU/cache on the layout/record-walk probes — implements scene-memory.md §2.6), but a
    /// correctness-sensitive data-structure migration (get-or-add / FreeSubtree ordering / NodeFlags first-insert side
    /// effects), so it must land type-by-type behind a green VerticalSlice + --screenshot diff. Dormant (marker applied
    /// nowhere).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ColdSlabGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var on = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.EnableColdSlabAttribute",
                    static (_, _) => true, static (_, _) => true);
            context.RegisterSourceOutput(on, static (spc, _) =>
                spc.AddSource("FluentGpu.Scene.ColdSlab.g.cs", SourceText.From(ColdSlabInfra, Encoding.UTF8)));
        }

        private const string ColdSlabInfra =
@"// <auto-generated/>
// GEN-17 cold side-table slab (emitted because [EnableColdSlab] is present). scene-memory.md §2.6.
#nullable enable
namespace FluentGpu.Scene
{
    /// <summary>Dense cold-slab: a node-indexed ref column over a packed value slab, replacing a sparse Dictionary&lt;int,T&gt;.
    /// Get-or-add, free-list reuse and first-insert semantics must mirror the table it replaces (verified by the gates).</summary>
    internal sealed class ColdSlab<T> where T : struct
    {
        private int[] _column = global::System.Array.Empty<int>(); // node index -> slab slot+1 (0 = absent)
        private T[] _slab = global::System.Array.Empty<T>();
        private int _count;
        public ref T GetOrAdd(int node)
        {
            if ((uint)node >= (uint)_column.Length) global::System.Array.Resize(ref _column, global::System.Math.Max(node + 1, 16));
            int slot = _column[node];
            if (slot == 0) { if (_count == _slab.Length) global::System.Array.Resize(ref _slab, global::System.Math.Max(_slab.Length * 2, 16)); slot = ++_count; _column[node] = slot; }
            return ref _slab[slot - 1];
        }
        public bool Contains(int node) => (uint)node < (uint)_column.Length && _column[node] != 0;
        public void Remove(int node) { if ((uint)node < (uint)_column.Length) _column[node] = 0; }
    }
}
";
    }
}
