using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using FluentGpu.SourceGen.Localization;

namespace FluentGpu.SourceGen.Engine
{
    /// <summary>
    /// Control-kit glyph generator — <c>GlyphTableGenerator</c>. Emits the <c>public const string</c> surface of
    /// <c>FluentGpu.Controls.Icons</c> from a <c>glyphs.json</c> AdditionalFile (JSON source of truth, per the
    /// "improve, don't port: JSON over XML" preference). Each entry <c>"Play": "E768"</c> becomes
    /// <c>public const string Play = "";</c> — the identical surface, so ZERO call sites change.
    ///
    /// <para><b>Dormant-safe.</b> The generator only produces output when a <c>glyphs.json</c> AdditionalFile is present
    /// (marked <c>FluentGpuGlyphs="true"</c> or matching the <c>glyphs.json</c> path convention). Only the Controls
    /// project declares one, so the shared analyzer emits nothing in the Engine / app compilations.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class GlyphTableGenerator : IIncrementalGenerator
    {
        // <AdditionalFiles Include="glyphs.json" FluentGpuGlyphs="true" /> surfaced via
        //   <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="FluentGpuGlyphs" />.
        private const string MetadataKey = "build_metadata.AdditionalFiles.FluentGpuGlyphs";
        private const string PathConvention = "glyphs.json";
        private const string Ns = "FluentGpu.Controls";
        private const string ClassName = "Icons";

        private static readonly DiagnosticDescriptor MalformedJson = new(
            id: "FGGLYPH001",
            title: "Glyph table JSON could not be fully parsed",
            messageFormat: "The glyph table '{0}' could not be fully parsed ({1}); the entries parsed before the error were still emitted",
            category: "FluentGpu.Glyphs",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor BadCodepoint = new(
            id: "FGGLYPH002",
            title: "Glyph codepoint is not 4 hex digits",
            messageFormat: "Glyph '{0}' has codepoint '{1}', which is not a 4-hex-digit BMP codepoint; the entry was skipped",
            category: "FluentGpu.Glyphs",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var glyphTexts = context.AdditionalTextsProvider
                .Combine(context.AnalyzerConfigOptionsProvider)
                .Select(static (pair, ct) =>
                {
                    AdditionalText text = pair.Left;
                    var opts = pair.Right.GetOptions(text);
                    bool marked = opts.TryGetValue(MetadataKey, out string? v) && v is not null &&
                                  v.Equals("true", StringComparison.OrdinalIgnoreCase);
                    bool convention = text.Path.Replace('\\', '/').EndsWith(PathConvention, StringComparison.OrdinalIgnoreCase);
                    if (!marked && !convention) return default(GlyphFile?);
                    return new GlyphFile(text.Path, text.GetText(ct)?.ToString() ?? string.Empty);
                })
                .Where(static x => x is not null)
                .Select(static (x, _) => x!.Value);

            context.RegisterSourceOutput(glyphTexts.Collect(), static (spc, files) =>
            {
                if (files.IsDefaultOrEmpty) return;   // no glyphs.json in this compilation → dormant
                foreach (GlyphFile f in files.Sort(static (a, b) => string.CompareOrdinal(a.Path, b.Path)))
                    EmitFile(spc, f);
            });
        }

        private static void EmitFile(SourceProductionContext spc, GlyphFile f)
        {
            var pairs = TinyJsonReader.Parse(f.Content, out bool hadError, out string? error);
            if (hadError)
                spc.ReportDiagnostic(Diagnostic.Create(MalformedJson, Location.None, f.Path, error ?? "unknown error"));

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n");
            sb.Append("// Generated by FluentGpu.SourceGen (Engine/GlyphTableGenerator) from glyphs.json — DO NOT EDIT.\n");
            sb.Append("#nullable enable\n\n");
            sb.Append("namespace ").Append(Ns).Append("\n{\n");
            sb.Append("    public static partial class ").Append(ClassName).Append("\n    {\n");

            foreach (KeyValuePair<string, string> kv in pairs)
            {
                string name = kv.Key;
                string cp = kv.Value.Trim();
                if (!IsHex4(cp))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(BadCodepoint, Location.None, name, kv.Value));
                    continue;
                }
                string hex = cp.ToUpperInvariant();
                sb.Append("        /// <summary>Glyph U+").Append(hex).Append(".</summary>\n");
                sb.Append("        public const string ").Append(name).Append(" = \"\\u").Append(hex).Append("\";\n");
            }

            sb.Append("    }\n}\n");
            spc.AddSource(ClassName + ".Glyphs.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static bool IsHex4(string s)
        {
            if (s.Length != 4) return false;
            foreach (char c in s)
                if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'))) return false;
            return true;
        }

        private readonly struct GlyphFile : IEquatable<GlyphFile>
        {
            public readonly string Path;
            public readonly string Content;
            public GlyphFile(string path, string content) { Path = path; Content = content; }
            public bool Equals(GlyphFile other) => Path == other.Path && Content == other.Content;
            public override bool Equals(object? obj) => obj is GlyphFile o && Equals(o);
            public override int GetHashCode() => unchecked((Path?.GetHashCode() ?? 0) * 397 ^ (Content?.GetHashCode() ?? 0));
        }
    }
}
