using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace FluentGpu.SourceGen.Engine
{
    // ════════════════════════════════════════════════════════════════════════════════════════════════════════════
    //  THE REJECTED SET — built per the user's explicit "full toolkit now, gated" directive.
    //
    //  The source-generator investigation (docs/plans/source-generators-opportunity-investigation.md) VERIFIED each
    //  of these as net-negative AS A GENERATOR: the target is already optimal, the win is negligible, or the
    //  maintenance + canon cost of a Roslyn generator exceeds it. They are built here as REAL but DORMANT generators
    //  — each triggers on a marker attribute (emitted below) that no engine code applies, so each emits nothing and
    //  cannot regress the build. Each carries its verdict + evidence inline. Activating one is an explicit opt-in.
    // ════════════════════════════════════════════════════════════════════════════════════════════════════════════

    /// <summary>Emits the (dormant) trigger attributes for the rejected-set generators. Internal, post-init.</summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class RejectedSetMarkers : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context) =>
            context.RegisterPostInitializationOutput(static ctx =>
                ctx.AddSource("FluentGpu.CodeGen.RejectedSetAttributes.g.cs", SourceText.From(Src, Encoding.UTF8)));

        private const string Src =
@"// <auto-generated/>
// Trigger attributes for the rejected-set generators (verified net-negative; built dormant). Internal per-assembly.
#nullable enable
namespace FluentGpu.CodeGen
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class MotionTokensAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Struct | global::System.AttributeTargets.Class)] internal sealed class DrawOpAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class StaticGridAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class FastMeasureAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Class)] internal sealed class ReactiveGraphAttribute : global::System.Attribute { }
    [global::System.AttributeUsage(global::System.AttributeTargets.Method)] internal sealed class SpanFormatAttribute : global::System.Attribute { }
}
";
    }

    /// <summary>
    /// <b>GEN-07 — BakedMotionTokenGenerator (REJECTED: net-negative).</b> Folds a <c>[MotionTokens]</c> class's
    /// <c>MotionTok.Get</c> into a <c>static readonly MotionTokenDef[]</c> indexed by id. Verdict: the live
    /// <c>MotionTok</c> lookup is already a static-readonly access; a bounds-checked array index is comparable or a
    /// regression. Dormant (no <c>[MotionTokens]</c> in the engine).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class BakedMotionTokenGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.MotionTokensAttribute",
                    static (_, _) => true,
                    static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".MotionTable.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-07: bake the [MotionTok] fields to a flat MotionTokenDef[] + Get(id). (Dormant; net-negative.)\n" +
                    "    internal static class " + m.Name + "MotionTable\n    {\n" +
                    "        public static global::FluentGpu.Animation.MotionTokenDef Get(int id) => Table[id];\n" +
                    "        private static readonly global::FluentGpu.Animation.MotionTokenDef[] Table = global::System.Array.Empty<global::FluentGpu.Animation.MotionTokenDef>();\n    }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-09 — DrawListOpcodeCodec (REJECTED: maintainability, not speed).</b> Single-source-of-truth Encode/Decode
    /// for a <c>[DrawOp]</c> POD opcode struct. Verdict: the live DrawList encode is already a <c>MemoryMarshal.Write</c>
    /// blit — a generated codec mirrors an already-tight path for zero runtime win. Dormant (no <c>[DrawOp]</c>).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class DrawListOpcodeCodec : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.DrawOpAttribute",
                    static (_, _) => true,
                    static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".OpCodec.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-09: blittable Encode/Decode for the opcode POD. (Dormant; mirrors the live MemoryMarshal blit.)\n" +
                    "    internal static class " + m.Name + "Codec\n    {\n" +
                    "        public static void Encode(in " + m.Fqn + " op, global::System.Span<byte> dst) => global::System.Runtime.InteropServices.MemoryMarshal.Write(dst, in op);\n" +
                    "        public static " + m.Fqn + " Decode(global::System.ReadOnlySpan<byte> src) => global::System.Runtime.InteropServices.MemoryMarshal.Read<" + m.Fqn + ">(src);\n    }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-12 — GridTrackTableGenerator (REJECTED).</b> Precomputes a static <c>TrackSize[]</c> for a
    /// <c>[StaticGrid]</c> template. Verdict: the per-construction <c>TrackSize[]</c> the app builds is already
    /// hoisted/memoized app-side — no per-frame cost to remove. Dormant (no <c>[StaticGrid]</c>).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class GridTrackTableGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.StaticGridAttribute",
                    static (_, _) => true,
                    static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".GridTracks.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-12: precomputed track table for a structurally-fixed grid. (Dormant; already hoisted app-side.)\n" +
                    "    internal static class " + m.Name + "Tracks\n    {\n" +
                    "        public static readonly global::FluentGpu.Foundation.TrackSize[] Columns = global::System.Array.Empty<global::FluentGpu.Foundation.TrackSize>();\n    }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-03 — ElementDispatchTable (REJECTED: likely slower than the int compare).</b> A <c>delegate*</c> reconcile
    /// dispatch table over <c>[Element]</c> types. Verdict: the live reconciler already dispatches on the <c>ushort
    /// ElementTypeId</c> (an int compare); a function-pointer table is comparable or slower and loses the JIT switch.
    /// Dormant (no record carries <c>[Element]</c>).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ElementDispatchTableGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.ElementAttribute", static (_, _) => true, static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".Dispatch.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-03: per-type reconcile dispatch entry. (Dormant; rejected — the live ushort ElementTypeId\n" +
                    "    // int-compare beats a function-pointer table.)\n" +
                    "    internal static partial class " + m.Name + "Dispatch { }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-11 — SpecializedMeasureGenerator (REJECTED).</b> A specialized measure/arrange routine for a
    /// <c>[FastMeasure]</c> structurally-fixed control template, bypassing the generic flex solver. Verdict: the
    /// generic solver is not a measured bottleneck and the specialized path duplicates layout logic at high risk.
    /// Dormant (no <c>[FastMeasure]</c>).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SpecializedMeasureGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.FastMeasureAttribute", static (_, _) => true, static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".Measure.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-11: specialized measure for a fixed template. (Dormant; rejected — generic solver not a bottleneck.)\n" +
                    "    internal static partial class " + m.Name + "Measure { }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-13 — BakedAcrylicGenerator (REJECTED: premise refuted).</b> Bake the theme-aware Acrylic/Shadow getters
    /// of a <c>[ThemeTokens]</c> class to per-theme statics. Verdict: those getters are already static-readonly reads
    /// (no per-read divides) — the premise is refuted. Dormant (no <c>[ThemeTokens]</c>; folds into GEN-08 if ever built).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class BakedAcrylicGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.ThemeTokensAttribute", static (_, _) => true, static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".BakedAcrylic.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-13: per-theme baked Acrylic/Shadow statics. (Dormant; premise refuted — already static-readonly.)\n" +
                    "    internal static partial class " + m.Name + "BakedAcrylic { }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>
    /// <b>GEN-15 — SignalGraphSpecializer (REJECTED).</b> Compile-time specialization of a <c>[ReactiveGraph]</c>'s
    /// subscribe/relink to eliminate the per-read subscriber scan. Verdict: the live <c>_subs</c> scan is over a 1–4
    /// element list — no measurable cost. Dormant (no <c>[ReactiveGraph]</c>).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SignalGraphSpecializer : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    "FluentGpu.CodeGen.ReactiveGraphAttribute", static (_, _) => true, static (ctx, _) => Gen.Type(ctx))
                .Where(static m => m.Name is not null);
            context.RegisterSourceOutput(models, static (spc, m) => spc.AddSource(
                m.Name + ".SignalGraph.g.cs",
                SourceText.From(Gen.Wrap(m.Ns, m.Name!,
                    "    // GEN-15: specialized signal subscribe/relink. (Dormant; rejected — scan is over a 1-4 element list.)\n" +
                    "    internal static partial class " + m.Name + "SignalGraph { }\n"),
                    Encoding.UTF8)));
        }
    }

    /// <summary>Shared helpers for the rejected-set generators.</summary>
    internal static class Gen
    {
        /// <summary>Extract (namespace, type name, fully-qualified name) from an attributed type target.</summary>
        public static (string? Ns, string? Name, string Fqn) Type(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol t) return (null, null, "");
            string? ns = t.ContainingNamespace.IsGlobalNamespace ? null : t.ContainingNamespace.ToDisplayString();
            return (ns, t.Name, t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        public static string Wrap(string? ns, string typeName, string body)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n// Generated by FluentGpu.SourceGen (rejected-set; built dormant per the full-toolkit directive).\n#nullable enable\n\n");
            bool hasNs = ns is not null;
            if (hasNs) sb.Append("namespace ").Append(ns).Append("\n{\n");
            sb.Append(body);
            if (hasNs) sb.Append("}\n");
            return sb.ToString();
        }
    }
}
