using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentGpu.SourceGen.Engine
{
    /// <summary>
    /// Engine DSL generator #5 — <c>ThemeBlobGenerator</c> (design/subsystems/dsl-aot.md §2.5; GEN-08).
    ///
    /// <para><b>Trigger:</b> <c>[FluentGpu.CodeGen.ThemeTokens]</c> on the partial token class. <b>Emits</b> a
    /// <c>enum TokenId : ushort</c> over the class's <c>ColorF</c> token properties + a <c>Resolve(TokenId, ThemeKind)</c>
    /// indexer over per-theme tables — the indexer the (unbuilt) BrushDeriver / T1 / T2 tiers need to converge onto one
    /// <c>BrushHandle</c>.</para>
    ///
    /// <para><b>STATUS (source-gen investigation):</b> build-later — LOW impact (startup-only: it would elide ~2.6 KB of
    /// one-time <c>TokenSet</c> allocation + ~596 <c>FromRgba</c> divides; the steady-state read is ALREADY a static-field
    /// load). Its justification is ENABLEMENT for the BrushDeriver, which is not built — so it is premature, and
    /// DORMANT here (<c>Tok</c> is not annotated <c>[ThemeTokens]</c>; replacing the live <c>BuildDark/BuildLight</c>
    /// would risk the 528-gate theme system and require <c>Tok</c> to stay a hand shim over the tables for accent
    /// folding/overrides). Wave 1 emits the <c>TokenId</c> enum + <c>Resolve</c> shape; the actual baked byte blob lands
    /// with the BrushDeriver, when the value source-of-truth moves into a generator-readable manifest.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ThemeBlobGenerator : IIncrementalGenerator
    {
        private const string ThemeTokensAttr = "FluentGpu.CodeGen.ThemeTokensAttribute";
        // dsl-aot.md §2.5 drift note: the doc said BrushSpec; the LIVE token type is ColorF (Foundation/Geometry.cs).
        private const string ColorType = "FluentGpu.Foundation.ColorF";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var models = context.SyntaxProvider.ForAttributeWithMetadataName(
                    ThemeTokensAttr,
                    predicate: static (_, _) => true,
                    transform: static (ctx, ct) => Extract(ctx, ct))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!.Value);

            context.RegisterSourceOutput(models, static (spc, model) =>
                spc.AddSource(model.HintName + ".ThemeBlob.g.cs", SourceText.From(Emit(model), Encoding.UTF8)));
        }

        private static Model? Extract(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
            var tokens = ImmutableArray.CreateBuilder<string>();
            foreach (ISymbol member in type.GetMembers())
            {
                ct.ThrowIfCancellationRequested();
                // Only the flat ColorF tokens bake into the blob; heterogeneous tokens (e.g. AcrylicSpec) stay on the
                // hand shim (the §2.5 "too simple to be a flat Cast<byte,ColorF>[id]" caveat).
                if (member is IPropertySymbol { IsStatic: false } p && p.Type.ToDisplayString() == ColorType)
                    tokens.Add(p.Name);
            }
            if (tokens.Count == 0) return null;
            return new Model(
                type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
                type.Name, Sanitize(type.ToDisplayString()), tokens.ToImmutable());
        }

        private static string Emit(Model m)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n// Generated by FluentGpu.SourceGen (Engine/ThemeBlobGenerator, GEN-08) — DO NOT EDIT.\n#nullable enable\n\n");
            bool hasNs = m.Namespace is not null;
            string pad = hasNs ? "    " : "";
            if (hasNs) sb.Append("namespace ").Append(m.Namespace).Append("\n{\n");

            sb.Append(pad).Append("/// <summary>Stable token ids for <c>").Append(m.TypeName).Append("</c> (generated, GEN-08).</summary>\n");
            sb.Append(pad).Append("internal enum ").Append(m.TypeName).Append("TokenId : ushort\n").Append(pad).Append("{\n");
            foreach (string t in m.Tokens) sb.Append(pad).Append("    ").Append(t).Append(",\n");
            sb.Append(pad).Append("    Count\n").Append(pad).Append("}\n\n");

            sb.Append(pad).Append("internal static class ").Append(m.TypeName).Append("Blob\n").Append(pad).Append("{\n");
            sb.Append(pad).Append("    // GEN-08: per-theme ColorF tables + Resolve(id, theme). The actual baked values land\n");
            sb.Append(pad).Append("    // with the BrushDeriver (when the value source-of-truth moves to a generator manifest).\n");
            sb.Append(pad).Append("    private static readonly global::").Append(ColorType).Append("[] _dark = new global::").Append(ColorType).Append("[(int)").Append(m.TypeName).Append("TokenId.Count];\n");
            sb.Append(pad).Append("    private static readonly global::").Append(ColorType).Append("[] _light = new global::").Append(ColorType).Append("[(int)").Append(m.TypeName).Append("TokenId.Count];\n");
            sb.Append(pad).Append("    public static global::").Append(ColorType).Append(" Resolve(").Append(m.TypeName).Append("TokenId id, global::FluentGpu.Dsl.ThemeKind theme)\n");
            sb.Append(pad).Append("        => (theme == global::FluentGpu.Dsl.ThemeKind.Light ? _light : _dark)[(int)id];\n");
            sb.Append(pad).Append("}\n");

            if (hasNs) sb.Append("}\n");
            return sb.ToString();
        }

        private static string Sanitize(string s)
        {
            var sb = new StringBuilder(s.Length);
            foreach (char c in s) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }

        private readonly record struct Model(string? Namespace, string TypeName, string HintName, ImmutableArray<string> Tokens);
    }
}
