using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentGpu.SourceGen.Engine
{
    /// <summary>
    /// Engine token generator — <c>TokAccessorGenerator</c>. Emits the one-line <c>public static X Foo => T.Foo;</c>
    /// forwarding getters on <c>partial class Tok</c> from the <c>TokenSet</c> record's fields, so a new semantic brush
    /// added to <c>TokenSet</c> can no longer silently do nothing until someone hand-adds the accessor (the drift the
    /// hand-written getters invited).
    ///
    /// <para><b>Only pure forwards are generated.</b> For each settable public <c>TokenSet</c> property, a getter is
    /// emitted ONLY IF <c>Tok</c> does not already declare a member of that name. Getters WITH LOGIC (accent-aware
    /// shades, memoized GradientSpecs, theme-keyed icon layers, the override-aware WindowBackground) stay hand-written
    /// in <c>Tokens.cs</c> and win automatically — the generator sees them on the partial and skips those names.</para>
    ///
    /// <para><b>Dormant-safe.</b> The getters forward to <c>Tok.T</c>, which lives with <c>TokenSet</c> in the Engine
    /// assembly, so the generator emits ONLY into the compilation that DECLARES both types in source. In a consumer
    /// project (Controls / WindowsApp) <c>TokenSet</c>/<c>Tok</c> are referenced metadata (a different
    /// <c>ContainingAssembly</c>), so the generator produces nothing there.</para>
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class TokAccessorGenerator : IIncrementalGenerator
    {
        private const string TokenSetName = "FluentGpu.Dsl.TokenSet";
        private const string TokName = "FluentGpu.Dsl.Tok";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var model = context.CompilationProvider.Select(static (comp, ct) => Extract(comp, ct));
            context.RegisterSourceOutput(model, static (spc, m) =>
            {
                if (m is null) return;
                spc.AddSource("Tok.Accessors.g.cs", SourceText.From(Emit(m.Value), Encoding.UTF8));
            });
        }

        private static Model? Extract(Compilation comp, CancellationToken ct)
        {
            INamedTypeSymbol? tokenSet = comp.GetTypeByMetadataName(TokenSetName);
            INamedTypeSymbol? tok = comp.GetTypeByMetadataName(TokName);
            if (tokenSet is null || tok is null) return null;

            // Only the assembly that OWNS the source of both types (the Engine) gets output — never a consumer where
            // they arrive as referenced metadata (the "no other consumer project misfires" guard).
            if (!SymbolEqualityComparer.Default.Equals(tokenSet.ContainingAssembly, comp.Assembly)) return null;
            if (!SymbolEqualityComparer.Default.Equals(tok.ContainingAssembly, comp.Assembly)) return null;

            // Names Tok already declares (hand-written partial: fields + properties) — a getter with logic wins.
            var declared = new HashSet<string>(StringComparer.Ordinal);
            foreach (ISymbol member in tok.GetMembers())
                if (member is IPropertySymbol || member is IFieldSymbol) declared.Add(member.Name);

            var props = ImmutableArray.CreateBuilder<PropInfo>();
            foreach (ISymbol member in tokenSet.GetMembers())
            {
                ct.ThrowIfCancellationRequested();
                if (member is not IPropertySymbol p || p.IsStatic || p.IsIndexer) continue;
                if (p.DeclaredAccessibility != Accessibility.Public || p.GetMethod is null) continue;
                if (declared.Contains(p.Name)) continue;   // hand-written getter with logic — leave it
                props.Add(new PropInfo(p.Name, p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
            }
            if (props.Count == 0) return null;
            props.Sort(static (a, b) => string.CompareOrdinal(a.Name, b.Name));   // deterministic output order
            return new Model(props.ToImmutable());
        }

        private static string Emit(Model m)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n");
            sb.Append("// Generated by FluentGpu.SourceGen (Engine/TokAccessorGenerator) — DO NOT EDIT.\n");
            sb.Append("// One `public static X Foo => T.Foo;` per TokenSet field WITHOUT a hand-written Tok getter.\n");
            sb.Append("#nullable enable\n\n");
            sb.Append("namespace FluentGpu.Dsl\n{\n");
            sb.Append("    public static partial class Tok\n    {\n");
            foreach (PropInfo p in m.Props)
                sb.Append("        public static ").Append(p.TypeFqn).Append(' ').Append(p.Name)
                  .Append(" => T.").Append(p.Name).Append(";\n");
            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        private readonly record struct PropInfo(string Name, string TypeFqn);
        private readonly record struct Model(ImmutableArray<PropInfo> Props);
    }
}
