# Extracts WinUI-Gallery metadata for the fluent-gpu capability gallery:
#   1. Per-control metadata (subtitle, description, learn.microsoft.com doc links, related controls, WinUI
#      template SourcePath, tile image) from WinUI-Gallery's ControlInfoData.json -> PageInfoData.g.cs
#   2. Copies the control tile PNGs we reference into src/FluentGpu.WindowsApp/assets/ControlImages
#   3. Converts the full Segoe Fluent Icons catalog (IconsData.json) -> assets/IconsData.tsv (Code \t Name \t tags)
# Requires a sibling checkout of https://github.com/microsoft/WinUI-Gallery at C:\WAVEE\WinUI-Gallery.
#   powershell -File scripts\extract-gallery-metadata.ps1

$ErrorActionPreference = 'Stop'
$galleryRoot = 'C:\WAVEE\WinUI-Gallery\WinUIGallery'
$repo = Split-Path -Parent $PSScriptRoot
$appDir = Join-Path $repo 'src\FluentGpu.WindowsApp'
$assetDir = Join-Path $appDir 'assets\ControlImages'
$controlsDir = Join-Path $repo 'src\FluentGpu.Controls'

$data = Get-Content (Join-Path $galleryRoot 'SampleSupport\Data\ControlInfoData.json') -Raw | ConvertFrom-Json
$items = @{}
foreach ($g in $data.Groups) { foreach ($it in $g.Items) { $items[$it.UniqueId.ToLowerInvariant()] = $it } }

# Nav keys of every gallery page backed by a WinUI control (plus a few extras used by engine pages).
$keys = @(
  'Button','DropDownButton','HyperlinkButton','RepeatButton','ToggleButton','SplitButton','ToggleSplitButton',
  'CheckBox','ColorPicker','ComboBox','RadioButton','RatingControl','Slider','ToggleSwitch',
  'InfoBadge','InfoBar','ProgressBar','ProgressRing','ToolTip',
  'Expander','SplitView','Viewbox','Border','Canvas','RelativePanel','VariableSizedWrapGrid',
  'PipsPager','AnnotatedScrollBar',
  'BreadcrumbBar','SelectorBar','TabView','Pivot',
  'Flyout','ContentDialog','TeachingTip','Popup',
  'TextBox','PasswordBox','AutoSuggestBox','NumberBox','TextBlock','RichTextBlock',
  'PersonPicture','MediaPlayerElement',
  'ListView','GridView','FlipView','TreeView','ItemsView',
  'MenuBar','AppBarButton','AppBarToggleButton','CommandBar','AppBarSeparator','CommandBarFlyout','SwipeControl',
  'CalendarView','CalendarDatePicker','DatePicker','TimePicker',
  'ItemsRepeater','ScrollViewer','AnimatedIcon'
)

function Esc([string]$s) {
  if ($null -eq $s) { return '' }
  return $s.Replace('\', '\\').Replace('"', '\"').Replace("`r", '').Replace("`n", ' ')
}

# Engine control source overrides (nav key -> file in src/FluentGpu.Controls when not "{Key}.cs").
$srcOverrides = @{
  'Border' = 'BorderControl.cs'; 'Flyout' = 'GenericFlyout.cs'; 'TextBlock' = 'TextBlockDemo.cs'
  'ItemsRepeater' = 'Repeater.cs'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated/> Produced by scripts/extract-gallery-metadata.ps1 from WinUI-Gallery''s')
[void]$sb.AppendLine('// ControlInfoData.json (subtitle/description/doc-links/related/WinUI template path per control).')
[void]$sb.AppendLine('// Hand-edits belong in PageInfo.cs, which merges this table with the engine-page entries.')
[void]$sb.AppendLine('static partial class PageInfo')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    static readonly PageMeta[] WinUiMeta =')
[void]$sb.AppendLine('    [')
$missing = @()
foreach ($k in $keys) {
  $it = $items[$k.ToLowerInvariant()]
  if ($null -eq $it) { $missing += $k; continue }
  $img = $null
  if ($it.ImagePath) {
    $img = [System.IO.Path]::GetFileName($it.ImagePath)
    $srcPng = Join-Path $galleryRoot ("Assets\ControlImages\" + $img)
    if (Test-Path $srcPng) { Copy-Item $srcPng (Join-Path $assetDir $img) -Force } else { $img = $null }
  }
  $docs = @()
  foreach ($d in $it.Docs) { $docs += ('new("{0}", "{1}")' -f (Esc $d.Title), (Esc $d.Uri)) }
  $rel = @()
  foreach ($r in $it.RelatedControls) { $rel += ('"{0}"' -f (Esc $r)) }

  # Engine control source file (repo-relative), when one exists.
  $srcFile = if ($srcOverrides.ContainsKey($k)) { $srcOverrides[$k] } else { "$k.cs" }
  if (-not (Test-Path (Join-Path $controlsDir $srcFile))) { $srcFile = $null }
  $srcLit = if ($srcFile) { '"src/FluentGpu.Controls/' + $srcFile + '"' } else { 'null' }

  # Which gallery page file hosts this control's sample page (class {Key}Page / {Key}ControlPage).
  $pageFile = $null
  foreach ($f in Get-ChildItem $appDir -Filter '*.cs') {
    $content = Get-Content $f.FullName -Raw
    if ($content -match ("class\s+" + [regex]::Escape($k) + "(Control)?Page\b")) { $pageFile = $f.Name; break }
  }
  $pageLit = if ($pageFile) { '"src/FluentGpu.WindowsApp/' + $pageFile + '"' } else { 'null' }

  $tplLit = if ($it.SourcePath) { '"' + (Esc $it.SourcePath) + '"' } else { 'null' }
  $imgLit = if ($img) { '"' + $img + '"' } else { 'null' }

  [void]$sb.AppendLine(('        new("{0}", "{1}",' -f $k, (Esc $it.Subtitle)))
  [void]$sb.AppendLine(('            "{0}",' -f (Esc $it.Description)))
  [void]$sb.AppendLine(('            {0}, {1}, {2}, {3},' -f $imgLit, $tplLit, $srcLit, $pageLit))
  [void]$sb.AppendLine(('            [{0}],' -f ($docs -join ', ')))
  [void]$sb.AppendLine(('            [{0}]),' -f ($rel -join ', ')))
}
[void]$sb.AppendLine('    ];')
[void]$sb.AppendLine('}')
Set-Content -Path (Join-Path $appDir 'PageInfoData.g.cs') -Value $sb.ToString() -Encoding UTF8

# Full Segoe Fluent Icons catalog -> TSV (the new Iconography page parses this at mount; no JSON dependency).
$icons = Get-Content (Join-Path $galleryRoot 'Samples\Iconography\IconsData.json') -Raw | ConvertFrom-Json
$lines = foreach ($i in $icons) { "{0}`t{1}`t{2}" -f $i.Code, $i.Name, (($i.Tags) -join ',') }
Set-Content -Path (Join-Path $appDir 'assets\IconsData.tsv') -Value ($lines -join "`n") -Encoding UTF8

Write-Host ("icons: {0}" -f @($icons).Count)
Write-Host ("images now bundled: {0}" -f (Get-ChildItem $assetDir -Filter '*.png').Count)
if ($missing.Count) { Write-Host ("no ControlInfoData entry for: {0}" -f ($missing -join ', ')) }
