namespace FluentGpu.Controls;

/// <summary>
/// Standardized glyph constants (Segoe Fluent Icons / Segoe MDL2 Assets private-use codepoints) so icons are
/// consistent across the app. Use with Ui.Icon(Icons.Play) or IconButton.Create(Icons.Play, ...).
/// Font = Theme.IconFont by default; pass a custom "path.ttf#Family" for your own set.
///
/// <para>The <c>public const string</c> surface is GENERATED by <c>GlyphTableGenerator</c> (FluentGpu.SourceGen) from
/// <c>glyphs.json</c> — the single source of truth (per "improve, don't port: JSON over XML"). Add or change a glyph in
/// <c>glyphs.json</c>, not here; every name resolves to <c>"\uXXXX"</c> exactly as before. This partial keeps the type
/// declaration (and its doc); the generated partial supplies the members.</para>
/// </summary>
public static partial class Icons
{
}
