// <auto-generated>
// ThemedIcon starter data set.
//
// HARVESTED icons (Copy, Rename, Delete, Favorite, Share, Open, File, Folder, Link) are vector path data adapted from
// the Files app (https://github.com/files-community/Files), Files.App.Controls/ThemedIcon/Styles/Icons.*.xaml:
//
//     Copyright (c) Files Community. Licensed under the MIT License.
//
// The full MIT notice belongs in THIRD-PARTY-NOTICES. This file is normally REGENERATED by tools/themed-icon-import
// (an XmlReader over the Files Icons.*.xaml, never runtime XAML parsing); this seed set was hand-transcribed. The Files
// authoring view-box is 16 and the fill rule is EvenOdd (the WinUI PathGeometry default), preserved below.
//
// MUSIC icons (Play, Add, Heart, HeartFill) are hand-authored at a 16 view-box for this engine (no attribution).
// PlayNext / AddToQueue are the exact 24-viewbox outlines of the app's WaveeIcons rail glyphs (0xE900 / 0xE901,
// app/Wavee/assets/fonts/build-wavee-icons.py), split by contour into a neutral Base (the list lines) + an Accent
// (the play mark) for the two-tone shell treatment.
// </auto-generated>

namespace FluentGpu.Controls;

internal static class ThemedIconData
{
    // Files layers use EvenOdd (WinUI PathGeometry default) so counter-contours punch holes.
    private const bool EO = true;

    internal static void RegisterAll()
    {
        // ── Harvested from Files (MIT), 16 view-box, EvenOdd ─────────────────────────────────────────────────────────
        var copy = new IconDef(
            Outline: null, Filled: null, ViewBox: 16f, EvenOdd: EO, Layers:
            [
                new(IconRole.Alt, "m5,4.5h-1.5c-.53,0-1.04.21-1.41.59-.38.38-.59.88-.59,1.41v6c0,.53.21,1.04.59,1.41.38.38.88.59,1.41.59h4c.44,0,.87-.15,1.23-.42.35-.27.6-.65.71-1.08h-1.44c-.8,0-1.56-.32-2.12-.88-.56-.56-.88-1.33-.88-2.12v-5.5Z"),
                new(IconRole.Base, "m5,4h-1.5c-.66,0-1.3.26-1.77.73-.47.47-.73,1.1-.73,1.77v6c0,.66.26,1.3.73,1.77.47.47,1.1.73,1.77.73h4c.58,0,1.13-.2,1.58-.56.45-.36.75-.87.87-1.44h-1.03c-.1.29-.3.55-.55.73-.25.18-.56.28-.87.27H3.5c-.4,0-.78-.16-1.06-.44-.28-.28-.44-.66-.44-1.06v-6c0-.4.16-.78.44-1.06.28-.28.66-.44,1.06-.44h1.5v-1Z"),
                new(IconRole.Accent, "m6.5,9.5V3.5c0-.53.21-1.04.59-1.41.38-.38.88-.59,1.41-.59h4c.53,0,1.04.21,1.41.59.38.38.59.88.59,1.41v6c0,.53-.21,1.04-.59,1.41s-.88.59-1.41.59h-4c-.53,0-1.04-.21-1.41-.59-.38-.38-.59-.88-.59-1.41Z", 0.4f),
                new(IconRole.Accent, "m8.5,2c-.4,0-.78.16-1.06.44-.28.28-.44.66-.44,1.06v6c0,.4.16.78.44,1.06.28.28.66.44,1.06.44h4c.4,0,.78-.16,1.06-.44.28-.28.44-.66.44-1.06V3.5c0-.4-.16-.78-.44-1.06-.28-.28-.66-.44-1.06-.44h-4Zm-2.5,1.5c0-.66.26-1.3.73-1.77.47-.47,1.1-.73,1.77-.73h4c.66,0,1.3.26,1.77.73.47.47.73,1.1.73,1.77v6c0,.33-.06.65-.19.96s-.31.58-.54.81c-.23.23-.51.42-.81.54s-.63.19-.96.19h-4c-.66,0-1.3-.26-1.77-.73-.47-.47-.73-1.1-.73-1.77V3.5Z"),
            ]);
        ThemedIconRegistry.Register("Copy", copy);

        ThemedIconRegistry.Register("Rename", new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.AccentContrast, "m.5,4.5v7c0,1.1.9,2,2,2h7.5V2.5H2.5c-1.1,0-2,.9-2,2Zm13-2h-.5v11h.5c1.1,0,2-.9,2-2v-7c0-1.1-.9-2-2-2Z"),
            new(IconRole.Accent, "m13.5,15h-1.5V1h1.5c.28,0,.5-.22.5-.5S13.78,0,13.5,0h-4C9.22,0,9,.22,9,.5s.22.5.5.5h1.5v14h-1.5c-.28,0-.5.22-.5.5s.22.5.5.5h4c.28,0,.5-.22.5-.5s-.22-.5-.5-.5Zm-5.5-8H3c-.55,0-1,.45-1,1s.45,1,1,1h5c.55,0,1-.45,1-1s-.45-1-1-1Z"),
            new(IconRole.Base, "m13.5,2h-.5v1h.5c.83,0,1.5.67,1.5,1.5v7c0,.83-.67,1.5-1.5,1.5h-.5v1h.5c1.38,0,2.5-1.12,2.5-2.5v-7c0-1.38-1.12-2.5-2.5-2.5ZM0,4.5v7c0,1.38,1.12,2.5,2.5,2.5h7.5v-1H2.5c-.83,0-1.5-.67-1.5-1.5v-7c0-.83.67-1.5,1.5-1.5h7.5v-1H2.5c-1.38,0-2.5,1.12-2.5,2.5Z"),
        ]));

        ThemedIconRegistry.Register("Delete", new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.Alt, "m2,2.5h12l-1.24,10.79c-.15,1.26-1.21,2.21-2.48,2.21h-4.54c-1.27,0-2.34-.95-2.48-2.21L2,2.5Z"),
            new(IconRole.Base, "m13.5,2.5l-1.24,10.73c-.12,1.01-.97,1.77-1.99,1.77h-4.54c-1.02,0-1.87-.76-1.99-1.77L2.5,2.5h-1s0,.04,0,.06l1.24,10.79c.17,1.51,1.46,2.66,2.98,2.66h4.54c1.52,0,2.81-1.14,2.98-2.66l1.24-10.79s0-.04,0-.06h-1Zm-7,10c.28,0,.5-.22.5-.5v-6c0-.28-.22-.5-.5-.5s-.5.22-.5.5v6c0,.28.22.5.5.5Zm3,0c.28,0,.5-.22.5-.5v-6c0-.28-.22-.5-.5-.5s-.5.22-.5.5v6c0,.28.22.5.5.5Z"),
            new(IconRole.Accent, "m5,2v-.5C5,.67,5.67,0,6.5,0h3C10.33,0,11,.67,11,1.5v.5h4.5c.28,0,.5.22.5.5s-.22.5-.5.5H.5c-.28,0-.5-.22-.5-.5s.22-.5.5-.5h4.5Zm1-.5v.5h4v-.5c0-.28-.22-.5-.5-.5h-3c-.28,0-.5.22-.5.5Z"),
        ]));

        var favorite = new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.Alt, "m8.45,1.22c-.18-.37-.71-.37-.9,0l-2.03,4.12-4.54.66c-.41.06-.57.56-.28.85l3.29,3.2-.78,4.52c-.07.41.36.72.73.53l4.06-2.14,4.06,2.14c.37.19.8-.12.73-.53l-.78-4.52,3.29-3.2c.3-.29.13-.79-.28-.85l-4.41-.64-.13-.02-2.03-4.11Z"),
            new(IconRole.Base, "m7.1.9c.37-.74,1.43-.74,1.79,0l1.93,3.91,4.32.63c.82.12,1.15,1.13.55,1.71l-3.12,3.04.74,4.3c.14.82-.72,1.44-1.45,1.05l-3.86-2.03-3.86,2.03c-.73.39-1.59-.24-1.45-1.05l.74-4.3L.3,7.14c-.59-.58-.27-1.59.55-1.71l4.32-.63,1.93-3.91Zm.9.44l-1.93,3.91c-.15.3-.43.5-.75.55l-4.32.63,3.12,3.04c.24.23.34.56.29.89l-.74,4.3,3.86-2.03c.29-.15.64-.15.93,0l3.86,2.03-.74-4.3c-.06-.32.05-.66.29-.89l3.12-3.04-4.32-.63c-.33-.05-.61-.25-.75-.55l-1.93-3.91Z"),
        ]);
        ThemedIconRegistry.Register("Favorite", favorite);
        ThemedIconRegistry.Register("Like", favorite);   // alias

        ThemedIconRegistry.Register("Share", new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.Accent, "m11.43,10.07l4.07-4.07L11.43,1.93c-.16-.16-.43-.05-.43.18v1.9s-6.5.5-6.5,6.5c3.5-2.5,6.5-2.5,6.5-2.5v1.9c0,.22.27.33.43.18Z", 0.2f),
            new(IconRole.Base, "m3.5,2c-1.38,0-2.5,1.12-2.5,2.5v8c0,1.38,1.12,2.5,2.5,2.5h8c1.38,0,2.5-1.12,2.5-2.5v-1c0-.28-.22-.5-.5-.5s-.5.22-.5.5v1c0,.83-.67,1.5-1.5,1.5H3.5c-.83,0-1.5-.67-1.5-1.5v-8c0-.83.67-1.5,1.5-1.5h3c.28,0,.5-.22.5-.5s-.22-.5-.5-.5h-3Z"),
            new(IconRole.Accent, "m11.33,10.84l4.5-4.42.06-.07c.17-.23.15-.56-.06-.77L11.33,1.16l-.06-.05c-.36-.27-.89-.01-.89.47v2.13l-.22.02c-3.56.28-5.65,2.54-6.15,6.63-.06.53.54.85.93.51,1.43-1.28,2.91-2.07,4.44-2.39.25-.05.49-.09.74-.12l.26-.02v2.18c.07.45.61.67.95.33Zm-1.1-6.12l1.15-.08v-2.03l3.45,3.39-3.45,3.39v-2.16l-1.36.12h0c-1.7.18-3.31.86-4.83,2,.3-1.34.81-2.35,1.48-3.07.83-.89,1.99-1.44,3.56-1.57Z"),
        ]));

        var open = new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.AccentContrast, "M8 0.5C3.85786 0.5 0.5 3.85786 0.5 8C0.5 12.1421 3.85786 15.5 8 15.5C12.1421 15.5 15.5 12.1421 15.5 8C15.5 3.85786 12.1421 0.5 8 0.5Z"),
            new(IconRole.Accent, "M10.8514 5.14433C10.804 5.09744 10.7495 5.06198 10.6914 5.03794C10.6324 5.01349 10.5678 5 10.5 5H5.5C5.22386 5 5 5.22386 5 5.5C5 5.77614 5.22386 6 5.5 6H9.29289L5.14645 10.1464C4.95118 10.3417 4.95118 10.6583 5.14645 10.8536C5.34171 11.0488 5.65829 11.0488 5.85355 10.8536L10 6.70711V10.5C10 10.7761 10.2239 11 10.5 11C10.7761 11 11 10.7761 11 10.5V5.5C11 5.43221 10.9865 5.36756 10.9621 5.30861C10.938 5.25051 10.9026 5.19602 10.8557 5.14857L10.8514 5.14433Z"),
            new(IconRole.Base, "M8 0C12.4183 0 16 3.58172 16 8C16 12.4183 12.4183 16 8 16C3.58172 16 0 12.4183 0 8C0 3.58172 3.58172 0 8 0ZM15 8C15 4.13401 11.866 1 8 1C4.13401 1 1 4.13401 1 8C1 11.866 4.13401 15 8 15C11.866 15 15 11.866 15 8Z"),
        ]);
        ThemedIconRegistry.Register("Open", open);
        ThemedIconRegistry.Register("GoTo", open);   // alias (go to album/artist)

        ThemedIconRegistry.Register("File", new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.Alt, "M4 0.5C3.17157 0.5 2.5 1.17157 2.5 2V14C2.5 14.8284 3.17157 15.5 4 15.5H12C12.8284 15.5 13.5 14.8284 13.5 14V5.5H9.5C8.94772 5.5 8.5 5.05228 8.5 4.5V0.5H4Z"),
            new(IconRole.Base, "M4 0C2.89543 0 2 0.895431 2 2V14C2 15.1046 2.89543 16 4 16H12C13.1046 16 14 15.1046 14 14V5.41421C14 5.01639 13.842 4.63486 13.5607 4.35355L9.64645 0.43934C9.36514 0.158035 8.98361 0 8.58579 0H4ZM3 2C3 1.44772 3.44772 1 4 1H8V4.5C8 5.32843 8.67157 6 9.5 6H13V14C13 14.5523 12.5523 15 12 15H4C3.44772 15 3 14.5523 3 14V2ZM12.7929 5H9.5C9.22386 5 9 4.77614 9 4.5V1.20711L12.7929 5Z"),
        ]));

        // Folder: single Base (the outline path).
        ThemedIconRegistry.Register("Folder", new IconDef(
            Outline: "M2.5 1C1.11929 1 0 2.11929 0 3.5V12.5C0 13.8807 1.11929 15 2.5 15H13.5C14.8807 15 16 13.8807 16 12.5V5.5C16 4.11929 14.8807 3 13.5 3H7.70711L6.21967 1.51256C5.89148 1.18437 5.44636 1 4.98223 1H2.5ZM1 3.5C1 2.67157 1.67157 2 2.5 2H4.98223C5.18115 2 5.37191 2.07902 5.51256 2.21967L6.79289 3.5L5.43934 4.85355C5.34557 4.94732 5.21839 5 5.08579 5H1V3.5ZM1 6H5.08579C5.48361 6 5.86514 5.84196 6.14645 5.56066L7.70711 4H13.5C14.3284 4 15 4.67157 15 5.5V12.5C15 13.3284 14.3284 14 13.5 14H2.5C1.67157 14 1 13.3284 1 12.5V6Z",
            Filled: null, ViewBox: 16f, EvenOdd: EO, Layers: []));

        ThemedIconRegistry.Register("Link", new IconDef(null, null, ViewBox: 16f, EvenOdd: EO, Layers:
        [
            new(IconRole.AccentContrast, "m.5,8c0-1.93,1.57-3.5,3.5-3.5h8c1.93,0,3.5,1.57,3.5,3.5s-1.57,3.5-3.5,3.5H4c-1.93,0-3.5-1.57-3.5-3.5Z"),
            new(IconRole.Base, "m6,4c.28,0,.5.22.5.5,0,.25-.18.45-.41.49h-.09s-2,0-2,0c-1.66,0-3,1.34-3,3s1.24,2.89,2.8,2.99h.2s2,0,2,0c.28,0,.5.22.5.5,0,.25-.18.45-.41.49h-.09s-2,0-2,0c-2.21,0-4-1.79-4-4s1.67-3.88,3.78-3.99h.22s2,0,2,0Zm6,0c2.21,0,4,1.79,4,4s-1.67,3.88-3.78,3.99h-.22s-2,0-2,0c-.28,0-.5-.22-.5-.5,0-.25.18-.45.41-.49h.09s2,0,2,0c1.66,0,3-1.34,3-3s-1.24-2.89-2.8-2.99h-.2s-2,0-2,0c-.28,0-.5-.22-.5-.5,0-.25.18-.45.41-.49h.09s2,0,2,0Z"),
            new(IconRole.Accent, "m4,7.5h8c.28,0,.5.22.5.5,0,.25-.18.45-.41.49h-.09s-8,0-8,0c-.28,0-.5-.22-.5-.5,0-.25.18-.45.41-.49h.09s8,0,8,0H4Z"),
        ]));

        // ── Hand-authored music icons ────────────────────────────────────────────────────────────────────────────────
        // Play (24 view-box): a single Accent-filled Spotify-style triangle, CENTERED and sized to match the visual
        // weight of the PlayNext/AddToQueue play-mark contour (was a small triangle underfilling a 16-box). Base x=6→
        // apex x=20 (width 14), y=4→20 (height 16); centroid ≈ (10.7, 12) reads optically centred for a right-pointing
        // triangle. Nonzero winding, no hole.
        ThemedIconRegistry.Register("Play", new IconDef(null, null, ViewBox: 24f, EvenOdd: false, Layers:
        [
            new(IconRole.Accent, "M6 4 L20 12 L6 20 Z"),
        ]));

        // Add: a plus (accent).
        ThemedIconRegistry.Register("Add", new IconDef(null, null, ViewBox: 16f, EvenOdd: false, Layers:
        [
            new(IconRole.Accent, "M7 3 H9 V7 H13 V9 H9 V13 H7 V9 H3 V7 H7 Z"),
        ]));

        // PlayNext (0xE900 "Play next" — front of queue): the two-tone Files/shell treatment of the app's WaveeIcons
        // rail glyph. LIST LINES = neutral Base; the PLAY MARK entering the TOP of the list = Accent. Paths are the
        // exact 24-viewbox glyph outlines (app/Wavee/assets/fonts/build-wavee-icons.py), split by contour so the
        // themed strip icon mirrors the font glyph pixel-for-pixel; nonzero winding (matches the CFF glyph).
        ThemedIconRegistry.Register("PlayNext", new IconDef(null, null, ViewBox: 24f, EvenOdd: false, Layers:
        [
            new(IconRole.Base, "M21 5h-5a1 1 0 100 2h5a1 1 0 100-2Zm0 6H9a1 1 0 000 2h12a1 1 0 000-2Zm0 6H9a1 1 0 000 2h12a1 1 0 000-2Z"),
            new(IconRole.Accent, "M6 2.86V5H3a1 1 0 00-1 1v12a1 1 0 102 0V7h2v2.137a.5.5 0 00.748.434L13 5.998 6.748 2.426A.5.5 0 006 2.86Z"),
        ]));

        // AddToQueue (0xE901 "Play after" / add-to-queue — end of queue): same two-tone rail glyph, PLAY MARK entering
        // the BOTTOM of the list. LIST LINES = Base, play mark = Accent. Exact 24-viewbox glyph outlines; the two
        // list bars that followed the play mark in relative-move order are re-emitted here in absolute coordinates.
        ThemedIconRegistry.Register("AddToQueue", new IconDef(null, null, ViewBox: 24f, EvenOdd: false, Layers:
        [
            new(IconRole.Base, "M21 6.998a1 1 0 100-2H9a1 1 0 000 2h12ZM21 12.998a1 1 0 000-2H9a1 1 0 000 2h12ZM21 18.998a1 1 0 000-2h-5a1 1 0 000 2h5Z"),
            new(IconRole.Accent, "M6 21.138a.5.5 0 00.748.434L13 18l-6.252-3.573A.5.5 0 006 14.86V17H4V6a1 1 0 00-2 0v12a1 1 0 001 1h3v2.138Z"),
        ]));

        // Heart (unliked, 24 view-box): a neutral OUTLINE heart — one Base contour ring (outer heart minus an inner
        // heart offset ~2 units inward, EvenOdd punches the hole). Re-authored from the old 16-box heart (which filled
        // the whole box and read heavy) to a ~2-unit outline (renders ≈1.7px at 20px — same weight as the PlayNext
        // bars) with a ~4-unit inset all round so it sits in the strip as one family with PlayNext/AddToQueue. HeartFill
        // (liked): the same OUTER contour, Accent-filled. The labeled Like toggle swaps outline → accent-fill on check.
        ThemedIconRegistry.Register("Heart", new IconDef(null, null, ViewBox: 24f, EvenOdd: EO, Layers:
        [
            new(IconRole.Base,
                "M12 20 C12 20 4 14.5 4 8.75 C4 6 6.1 4 8.5 4 C10.1 4 11.4 4.95 12 6.3 C12.6 4.95 13.9 4 15.5 4 C17.9 4 20 6 20 8.75 C20 14.5 12 20 12 20 Z"
              + "M12 17.9 C12 17.9 6 13.6 6 9 C6 6.9 7.6 5.5 9.2 5.5 C10.3 5.5 11.4 6.15 12 7.25 C12.6 6.15 13.7 5.5 14.8 5.5 C16.4 5.5 18 6.9 18 9 C18 13.6 12 17.9 12 17.9 Z"),
        ]));

        ThemedIconRegistry.Register("HeartFill", new IconDef(null, null, ViewBox: 24f, EvenOdd: false, Layers:
        [
            new(IconRole.Accent,
                "M12 20 C12 20 4 14.5 4 8.75 C4 6 6.1 4 8.5 4 C10.1 4 11.4 4.95 12 6.3 C12.6 4.95 13.9 4 15.5 4 C17.9 4 20 6 20 8.75 C20 14.5 12 20 12 20 Z"),
        ]));
    }
}
